/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Candidates: () => import('#controllers/candidates_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Jobs: () => import('#controllers/jobs_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Sessions: () => import('#controllers/sessions_controller'),
}
