/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ApplicationNoteSchema extends BaseModel {
  static $columns = ['applicationId', 'authorId', 'content', 'createdAt', 'id', 'updatedAt'] as const
  $columns = ApplicationNoteSchema.$columns
  @column()
  declare applicationId: string
  @column()
  declare authorId: string
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ApplicationStatusHistorySchema extends BaseModel {
  static $columns = ['applicationId', 'changedByCandidateId', 'changedByType', 'changedByUserId', 'createdAt', 'fromStatus', 'id', 'reason', 'toStatus'] as const
  $columns = ApplicationStatusHistorySchema.$columns
  @column()
  declare applicationId: string
  @column()
  declare changedByCandidateId: string | null
  @column()
  declare changedByType: string
  @column()
  declare changedByUserId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fromStatus: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare reason: string | null
  @column()
  declare toStatus: string
}

export class ApplicationTagSchema extends BaseModel {
  static $columns = ['applicationId', 'createdAt', 'id', 'tagId'] as const
  $columns = ApplicationTagSchema.$columns
  @column()
  declare applicationId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare tagId: string
}

export class ApplicationSchema extends BaseModel {
  static $columns = ['appliedAt', 'candidateId', 'coverLetter', 'createdAt', 'cvDocumentId', 'hiredAt', 'id', 'jobId', 'rejectedAt', 'source', 'status', 'updatedAt'] as const
  $columns = ApplicationSchema.$columns
  @column.dateTime()
  declare appliedAt: DateTime
  @column()
  declare candidateId: string
  @column()
  declare coverLetter: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cvDocumentId: string | null
  @column.dateTime()
  declare hiredAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare jobId: string
  @column.dateTime()
  declare rejectedAt: DateTime | null
  @column()
  declare source: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CandidateDocumentSchema extends BaseModel {
  static $columns = ['candidateId', 'createdAt', 'filePath', 'fileSize', 'id', 'mimeType', 'name', 'type', 'updatedAt'] as const
  $columns = CandidateDocumentSchema.$columns
  @column()
  declare candidateId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare filePath: string
  @column()
  declare fileSize: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mimeType: string | null
  @column()
  declare name: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CandidateEducationSchema extends BaseModel {
  static $columns = ['candidateId', 'createdAt', 'degree', 'description', 'endDate', 'fieldOfStudy', 'id', 'institution', 'location', 'startDate', 'updatedAt'] as const
  $columns = CandidateEducationSchema.$columns
  @column()
  declare candidateId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare degree: string | null
  @column()
  declare description: string | null
  @column.date()
  declare endDate: DateTime | null
  @column()
  declare fieldOfStudy: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare institution: string | null
  @column()
  declare location: string | null
  @column.date()
  declare startDate: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CandidateExperienceSchema extends BaseModel {
  static $columns = ['candidateId', 'company', 'createdAt', 'description', 'endDate', 'id', 'isCurrent', 'location', 'position', 'startDate', 'updatedAt'] as const
  $columns = CandidateExperienceSchema.$columns
  @column()
  declare candidateId: string
  @column()
  declare company: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column.date()
  declare endDate: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isCurrent: boolean | null
  @column()
  declare location: string | null
  @column()
  declare position: string | null
  @column.date()
  declare startDate: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CandidateSessionSchema extends BaseModel {
  static $columns = ['candidateId', 'createdAt', 'expiresAt', 'id', 'lastUsedAt', 'tokenHash', 'updatedAt'] as const
  $columns = CandidateSessionSchema.$columns
  @column()
  declare candidateId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare tokenHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CandidateSkillSchema extends BaseModel {
  static $columns = ['candidateId', 'createdAt', 'id', 'level', 'skillId', 'updatedAt', 'yearsOfExperience'] as const
  $columns = CandidateSkillSchema.$columns
  @column()
  declare candidateId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare level: string | null
  @column()
  declare skillId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare yearsOfExperience: number | null
}

export class CandidateVerificationTokenSchema extends BaseModel {
  static $columns = ['candidateId', 'createdAt', 'email', 'expiresAt', 'id', 'tokenHash', 'updatedAt', 'verifiedAt'] as const
  $columns = CandidateVerificationTokenSchema.$columns
  @column()
  declare candidateId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare tokenHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare verifiedAt: DateTime | null
}

export class CandidateSchema extends BaseModel {
  static $columns = ['avatarUrl', 'bio', 'city', 'country', 'createdAt', 'dateOfBirth', 'email', 'firstName', 'githubUrl', 'id', 'lastName', 'linkedinUrl', 'location', 'phone', 'portfolioUrl', 'updatedAt', 'websiteUrl'] as const
  $columns = CandidateSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column()
  declare bio: string | null
  @column()
  declare city: string | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.date()
  declare dateOfBirth: DateTime | null
  @column()
  declare email: string
  @column()
  declare firstName: string | null
  @column()
  declare githubUrl: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastName: string | null
  @column()
  declare linkedinUrl: string | null
  @column()
  declare location: string | null
  @column()
  declare phone: string | null
  @column()
  declare portfolioUrl: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare websiteUrl: string | null
}

export class EmailTemplateSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'id', 'isActive', 'name', 'organizationId', 'subject', 'type', 'updatedAt'] as const
  $columns = EmailTemplateSchema.$columns
  @column()
  declare body: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean | null
  @column()
  declare name: string
  @column()
  declare organizationId: string
  @column()
  declare subject: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EmailSchema extends BaseModel {
  static $columns = ['applicationId', 'body', 'candidateId', 'createdAt', 'error', 'failedAt', 'id', 'organizationId', 'recipient', 'sentAt', 'status', 'subject', 'templateId', 'type', 'updatedAt'] as const
  $columns = EmailSchema.$columns
  @column()
  declare applicationId: string | null
  @column()
  declare body: string | null
  @column()
  declare candidateId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare error: string | null
  @column.dateTime()
  declare failedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare organizationId: string
  @column()
  declare recipient: string
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare status: string | null
  @column()
  declare subject: string | null
  @column()
  declare templateId: string | null
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class EvaluationSchema extends BaseModel {
  static $columns = ['applicationId', 'comments', 'createdAt', 'evaluatorId', 'id', 'interviewId', 'recommendation', 'score', 'strengths', 'updatedAt', 'weaknesses'] as const
  $columns = EvaluationSchema.$columns
  @column()
  declare applicationId: string
  @column()
  declare comments: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare evaluatorId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare interviewId: string | null
  @column()
  declare recommendation: string | null
  @column()
  declare score: number | null
  @column()
  declare strengths: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare weaknesses: string | null
}

export class InterviewSchema extends BaseModel {
  static $columns = ['applicationId', 'createdAt', 'createdBy', 'duration', 'id', 'location', 'meetingUrl', 'notes', 'scheduledAt', 'status', 'type', 'updatedAt'] as const
  $columns = InterviewSchema.$columns
  @column()
  declare applicationId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string
  @column()
  declare duration: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare location: string | null
  @column()
  declare meetingUrl: string | null
  @column()
  declare notes: string | null
  @column.dateTime()
  declare scheduledAt: DateTime | null
  @column()
  declare status: string | null
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class JobSkillSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'jobId', 'level', 'required', 'skillId'] as const
  $columns = JobSkillSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare jobId: string
  @column()
  declare level: string | null
  @column()
  declare required: boolean | null
  @column()
  declare skillId: string
}

export class JobSchema extends BaseModel {
  static $columns = ['benefits', 'city', 'closingDate', 'country', 'createdAt', 'createdBy', 'description', 'employmentType', 'experienceLevel', 'id', 'location', 'organizationId', 'publishedAt', 'requirements', 'responsibilities', 'salaryCurrency', 'salaryMax', 'salaryMin', 'slug', 'status', 'title', 'updatedAt', 'workplaceType'] as const
  $columns = JobSchema.$columns
  @column()
  declare benefits: string | null
  @column()
  declare city: string | null
  @column.date()
  declare closingDate: DateTime | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string
  @column()
  declare description: string | null
  @column()
  declare employmentType: string | null
  @column()
  declare experienceLevel: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare location: string | null
  @column()
  declare organizationId: string
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare requirements: string | null
  @column()
  declare responsibilities: string | null
  @column()
  declare salaryCurrency: string | null
  @column()
  declare salaryMax: number | null
  @column()
  declare salaryMin: number | null
  @column()
  declare slug: string
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare workplaceType: string | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['createdAt', 'data', 'id', 'message', 'readAt', 'title', 'type', 'updatedAt', 'userId'] as const
  $columns = NotificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare data: any | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare message: string | null
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare title: string | null
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class OrganizationSchema extends BaseModel {
  static $columns = ['address', 'city', 'country', 'createdAt', 'description', 'email', 'id', 'industry', 'logoUrl', 'name', 'phone', 'size', 'slug', 'timezone', 'updatedAt', 'website'] as const
  $columns = OrganizationSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare city: string | null
  @column()
  declare country: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare industry: string | null
  @column()
  declare logoUrl: string | null
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column()
  declare size: string | null
  @column()
  declare slug: string
  @column()
  declare timezone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare website: string | null
}

export class SkillSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = SkillSchema.$columns
  @column()
  declare category: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TagSchema extends BaseModel {
  static $columns = ['color', 'createdAt', 'id', 'name', 'organizationId', 'updatedAt'] as const
  $columns = TagSchema.$columns
  @column()
  declare color: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare organizationId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarUrl', 'createdAt', 'email', 'emailVerifiedAt', 'firstName', 'id', 'lastLoginAt', 'lastName', 'organizationId', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare firstName: string | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column()
  declare lastName: string | null
  @column()
  declare organizationId: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
